[package]
name = "veilite-core"
version.workspace = true
edition.workspace = true

[dependencies]
aes.workspace = true
cbc.workspace = true
hmac.workspace = true
pbkdf2.workspace = true
sha1.workspace = true
sha2.workspace = true
thiserror.workspace = true
zeroize = { workspace = true, features = ["derive"] }
