[package]
name = "veilite-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "CLI for reading SQLCipher database snapshots"
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords = ["sqlcipher", "sqlite"]
categories = ["command-line-utilities", "database"]

[[bin]]
name = "veilite"
path = "src/main.rs"

[dependencies]
bstr.workspace = true
clap.workspace = true
rpassword.workspace = true
veilite-core.workspace = true
veilite-graphitesql.workspace = true
zeroize.workspace = true
